version: '3.8'

services:
  vote-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vote-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - elasticsearch
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/votey
      SPRING_DATASOURCE_USERNAME: kohuijae
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: votey
      POSTGRES_USER: kohuijae
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.5
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - backend
volumes:
  pgdata:

networks:
  backend:
