name: CI/CD for Spring Boot

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. gradlew 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Build
      - name: Build with Gradle
        run: ./gradlew clean build

      # 5. EC2로 .jar 복사
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/vote-backend-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/vote-backend/build/libs/"

      # 6. EC2에서 앱 실행
      - name: Run app on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "======== 🚀 EC2 배포 시작 ========"
            date
          
            echo "🔍 현재 실행 중인 프로세스 확인:"
            pgrep -af 'vote-backend-0.0.1-SNAPSHOT.jar' || echo "No process found"
          
            echo "🛑 기존 프로세스 종료 시도:"
            PID=$(pgrep -f 'vote-backend-0.0.1-SNAPSHOT.jar') && sudo kill $PID && echo "✅ 종료 완료 (PID=$PID)" || echo "⚠️ 종료할 프로세스 없음"
          
            echo "🧹 이전 로그 삭제"
            rm -f /home/ubuntu/vote-backend/nohup.out
          
            echo "🟢 vote-backend 실행 스크립트 호출"
            nohup /home/ubuntu/vote-backend/start-vote.sh > /dev/null 2>&1 &
          
            sleep 5
          
            echo "📄 로그 출력"
            head -n 20 /home/ubuntu/vote-backend/nohup.out || echo "로그 파일이 아직 없음"