name: Deploy Spring Boot via Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 1. 백엔드 디렉토리로 이동
            cd vote-backend

            # 2. 최신 코드 pull
            git pull origin main

            # 3. 기존 프로세스 종료
            pkill -f 'vote-backend-0.0.1-SNAPSHOT.jar' || true

            # 4. 빌드
            ./gradlew clean build

            # 5. 애플리케이션 재실행
            nohup java -jar build/libs/vote-backend-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
