name: Deploy Spring Boot via Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            bash /home/ubuntu/deploy.sh
#            # 1. 백엔드 디렉토리로 이동
#            cd vote-backend
#
#            # 2. 최신 코드 pull
#            git pull origin main
#
#            # 3. 이전 프로세스 종료
#            PID=$(pgrep -f 'vote-backend-0.0.1-SNAPSHOT.jar') && sudo kill $PID || echo "No previous process"
#
#            # 4. 빌드
#            ./gradlew clean build
#
#            # 5. 애플리케이션 백그라운드 실행 (절대경로 + 세션 분리)
#            sudo setsid java -jar /home/ubuntu/vote-backend/build/libs/vote-backend-0.0.1-SNAPSHOT.jar > /home/ubuntu/vote-backend/nohup.out 2>&1 < /dev/null &
#            sleep 5
